### ISSUE TITLE
High CPU usage after granting mic access

### ISSUE THREAD

**Issue by DoaJCBlogger** [MoonchildProductions/Basilisk#12]
The CPU usage increases to over 70% for a single core when I grant mic access on Discord, and to about 48% when I grant it on onlinehardwaretest.com's microphone test. This occurs in the latest version of Basilisk, 52.9.2020.03.11.

**Comment by wolfbeast** [comment]
So, what does a "single core" constitute for your hardware? What operating system are you on?
Is this a regression, i.e. you didn't see this cpu usage before? If so, when did this regress?
What are your sampling settings in your operating system/microphone settings? If too high then CPU load is normal because it needs to downsample on the fly.

**Comment by DoaJCBlogger** [comment]
My computer has 4 cores, so 70% of a single core would be about 18% in Task Manager and 48% would be 12%. I'm using Windows 7 Pro x64, and I can't tell whether it's a regression since I don't normally use this browser. My microphone is set to use 1 channel, 16 bit sampling at 44100 Hz.

**Comment by wolfbeast** [comment]
Sorry if I wasn't clear in asking, but what is your CPU? type/speed?

**Comment by DoaJCBlogger** [comment]
Intel Core 2 Quad Q9500 2.83 GHz.

**Comment by mattatobin** [comment]
An 8 year old processor. Time to upgrade.

**Comment by DoaJCBlogger** [comment]
It's not a problem for me. A friend asked me to test it and post the issue. I think the real issue is high CPU usage compared to other browsers.
